apiVersion: dfds.cloud/v1alpha1
kind: Component
metadata:
  name: Blaster
  description: Frontend service for selfservice platform
  namespace: selfservice
  labels:
    for-public-consumption: no
  annotations:
    dfds.cloud/auth: okta 
spec:
  type: service
  lifecycle: production
  owner: devex@example.com
  capability: DED-Infrastructure